# Generated by Django 5.1.1 on 2024-10-08 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kfd', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='last_name',
        ),
    ]
