# Generated by Django 5.1.1 on 2024-10-15 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kfd', '0004_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='product_price',
        ),
    ]
