# Generated by Django 5.1.1 on 2024-10-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kfd', '0005_rename_name_product_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
