# Generated by Django 5.1.1 on 2024-10-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kfd', '0010_remove_order_user_checkout_delete_cartitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='added_date',
        ),
        migrations.AddField(
            model_name='checkout',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
