# Generated by Django 5.1.1 on 2024-10-31 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kfd', '0012_checkout_added_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='user',
        ),
        migrations.AddField(
            model_name='checkout',
            name='chekout_reg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kfd.registration'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kfd.product'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='quantity',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
