# Generated by Django 5.1.1 on 2024-11-01 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kfd', '0014_remove_registration_email_alter_checkout_chekout_reg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='chekout_reg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kfd.registration'),
        ),
    ]
