# Generated by Django 5.1.1 on 2024-11-01 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kfd', '0015_alter_checkout_chekout_reg'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
