# Generated by Django 5.1.1 on 2024-11-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kfd', '0017_checkout_is_preparing'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='is_prepared',
            field=models.BooleanField(default=False),
        ),
    ]
