# Generated by Django 5.1.1 on 2024-11-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kfd', '0018_checkout_is_prepared'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
