# Generated by Django 5.1.1 on 2024-11-02 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kfd', '0019_checkout_is_delivered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='is_delivered',
            new_name='is_delivery_partner_arrived',
        ),
    ]
