# Generated by Django 5.1.1 on 2024-11-03 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kfd', '0020_rename_is_delivered_checkout_is_delivery_partner_arrived'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
