# Generated by Django 5.1.1 on 2024-11-04 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kfd', '0022_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='InStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_in', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_status', to='kfd.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='OutStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_out', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_status', to='kfd.supplier')),
            ],
        ),
    ]
