# Generated by Django 5.1.1 on 2024-11-18 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kfd', '0032_remove_checkout_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='Address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kfd.address'),
        ),
    ]
