# Generated by Django 5.1.1 on 2024-11-18 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kfd', '0034_remove_checkout_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='chekout_reg',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='product',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Checkout',
        ),
    ]
