# Generated by Django 5.1.1 on 2024-11-25 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kfd', '0040_checkout_chk_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='chk_address',
        ),
        migrations.AddField(
            model_name='checkout',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kfd.address'),
        ),
    ]
