# Generated by Django 5.1.1 on 2024-11-25 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kfd', '0041_remove_checkout_chk_address_checkout_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='address',
        ),
        migrations.AddField(
            model_name='checkout',
            name='chk_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkout_to_address', to='kfd.address'),
        ),
    ]
