# Generated by Django 5.1.1 on 2024-11-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kfd', '0042_remove_checkout_address_checkout_chk_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
