# Generated by Django 5.1.1 on 2024-11-26 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kfd', '0044_rename_address_address_current_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='current_location',
            new_name='address',
        ),
    ]
