# Generated by Django 5.1.1 on 2024-11-27 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kfd', '0045_rename_current_location_address_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='current_address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
