# Generated by Django 5.1.1 on 2024-11-28 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kfd', '0046_checkout_current_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address',
        ),
    ]
