# Generated by Django 5.1.1 on 2024-11-30 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kfd', '0047_remove_address_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier_status',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
