# Generated by Django 5.1.1 on 2024-11-30 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kfd', '0050_remove_supplier_status_supplier_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier_status',
            name='in_out',
        ),
        migrations.AddField(
            model_name='supplier_status',
            name='supplier_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier_status',
            name='supplier_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
