# Generated by Django 5.1.1 on 2024-11-30 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kfd', '0051_remove_supplier_status_in_out_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier_status',
            name='supplier_in',
        ),
        migrations.RemoveField(
            model_name='supplier_status',
            name='supplier_out',
        ),
        migrations.AddField(
            model_name='supplier_status',
            name='in_out',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
