# Generated by Django 5.1.1 on 2024-11-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kfd', '0052_remove_supplier_status_supplier_in_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier_status',
            old_name='in_out',
            new_name='In',
        ),
        migrations.AddField(
            model_name='supplier_status',
            name='Out',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
