# Generated by Django 5.1.1 on 2024-11-30 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kfd', '0054_rename_in_supplier_status_in_out_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='delivery_boy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_orders', to='kfd.registration'),
        ),
    ]
