# Generated by Django 5.1.1 on 2024-11-30 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kfd', '0055_checkout_delivery_boy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='chekout_reg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkout_orders', to='kfd.registration'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='delivery_boy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to='kfd.registration'),
        ),
    ]
