# Generated by Django 5.1.1 on 2024-11-30 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kfd', '0056_alter_checkout_chekout_reg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='chekout_reg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkouts_as_customer', to='kfd.registration'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='delivery_boy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkouts_as_delivery_boy', to='kfd.registration'),
        ),
    ]
