# Generated by Django 5.1.1 on 2024-12-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kfd', '0057_alter_checkout_chekout_reg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='is_delivered_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checkout',
            name='is_out_of_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
