# Generated by Django 5.1.1 on 2024-12-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kfd', '0058_checkout_is_delivered_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='supplier_status',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier_status',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier_status',
            name='location_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier_status',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
