# Generated by Django 5.1.1 on 2024-12-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kfd', '0059_checkout_latitude_checkout_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='is_delivered',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='is_delivered_status',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='is_delivery_partner_arrived',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='is_out_of_delivery',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='is_prepared',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='is_preparing',
        ),
        migrations.AddField(
            model_name='checkout',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Preparing', 'Preparing'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered')], default='Pending', max_length=20),
        ),
    ]
