# Generated by Django 5.1.1 on 2024-12-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kfd', '0062_supplier_status_address_supplier_status_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier_status',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
