# Generated by Django 5.1.1 on 2024-12-10 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kfd', '0063_supplier_status_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='supplier_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kfd.supplier_status'),
        ),
    ]
