# Generated by Django 5.1.1 on 2024-12-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kfd', '0064_checkout_supplier_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='supplier_status',
        ),
        migrations.AddField(
            model_name='address',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
