# Generated by Django 5.1.1 on 2024-12-11 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kfd', '0065_remove_checkout_supplier_status_address_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='address',
            name='longitude',
        ),
    ]
