# Generated by Django 5.1.1 on 2024-12-12 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kfd', '0066_remove_address_latitude_remove_address_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
