# Generated by Django 5.1.1 on 2024-12-13 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kfd', '0069_checkout_latitude_checkout_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='place_name',
        ),
    ]
